### ISSUE TITLE
When using closeOnTapOutside intercept tap gesture

### ISSUE THREAD

**Issue by victorelcaminas** [SimformSolutionsPvtLtd/SSToastMessage#4]
When using closeOnTapOutside the gesture should be intercepted and not go through to the underlying view, otherwise buttons, or tap gestures in other views are executed too, while the expected behaviour is to just hide the Toast.

**Comment by YagnikBavishi04** [comment]
Fixed issue with [2.0.0](https://github.com/SimformSolutionsPvtLtd/SSToastMessage/releases/tag/2.0.0).
