### ISSUE TITLE
Having a callback when toast did hide

### ISSUE THREAD

**Issue by Wh1rlw1nd** [SimformSolutionsPvtLtd/SSToastMessage#5]
It would be quite nice that there is a callback that says to us when animation is finished.

I am not sure, but it seems this is not possible at the moment.

**Comment by AnkitPanchal10** [comment]
This feature will be released with PR#4

**Comment by YagnikBavishi04** [comment]
Fixed issue with [2.0.0](https://github.com/SimformSolutionsPvtLtd/SSToastMessage/releases/tag/2.0.0).
