### ISSUE TITLE
When ToastMessage on .Top AutoCloses.  App no longer honors safe area

### ISSUE THREAD

**Issue by dstrickland67** [SimformSolutionsPvtLtd/SSToastMessage#6]
**Describe the bug**
When ToastMessage on .Top AutoCloses.  App no longer honors safe area

**To Reproduce**
1. Present toast  (copied directly from sample on github).
  .present(isPresented: $showSubmitConfirmation, type: .toast, position: .top, autohideDuration: 6, closeOnTap: true) {
                       /// create your own view for toast
                        self.createTopToastView()
                    }
 func createTopToastView() -> some View {
        VStack {
            Spacer(minLength: 20)
            HStack() {
                Image("mike")
                    .resizable()
                    .aspectRatio(contentMode: ContentMode.fill)
                    .frame(width: 50, height: 50)
                    .cornerRadius(25)

                VStack(alignment: .leading, spacing: 2) {
                    HStack {
                        Text("Mike")
                            .foregroundColor(.white)
                            .fontWeight(.bold)
                        Spacer()
                        Text("10:10")
                            .font(.system(size: 12))
                            .foregroundColor(Color(red: 0.9, green: 0.9, blue: 0.9))
                    }

                    Text("Hey, Don't miss the WWDC on tonight at 10 AM PST.")
                        .lineLimit(2)
                        .font(.system(size: 14))
                        .foregroundColor(.white)
                }
            }.padding(15)
        }
        .frame(width: UIScreen.main.bounds.width, height: 110)
        .background(Color(red: 0.85, green: 0.65, blue: 0.56))
    }

2. Let message auto close
3. top line of app is now inside unsafe area.  It is almost like the app is changing the main window to unsafe and not back when done.

**Expected behavior**

**Screenshots**
1. Before toast 
![image](https://user-images.githubusercontent.com/3538674/170839458-f4d3e1c0-5a04-4838-b260-46a5c3e70a6f.png)
2. Toast 
![image](https://user-images.githubusercontent.com/3538674/170839482-1a9849d3-200d-4e78-9a82-2bb5b84c0835.png)
3. After Toast
![image](https://user-images.githubusercontent.com/3538674/170839488-013c69f6-0636-449c-9a1d-30ee0fef1a1e.png)

**Smartphone (please complete the following information):**
 - Device: iPad mini 15.5 (simulator)
 - OS:IOS 15.5

**Additional context**

**Comment by YagnikBavishi04** [comment]
Unfortunately, we are unable to reproduce the issue mentioned above with your given code base. Please update to the new version [2.0.0](https://github.com/SimformSolutionsPvtLtd/SSToastMessage/releases/tag/2.0.0) and verify if the problem persists with the latest release.
